### ISSUE TITLE
duplicate username(display name) error on sign up

### ISSUE THREAD

**Issue by aubreezy0** [team-jorgie/team-project-front-end#22]
Display names ( #21 ) are currently required to be unique. As a result, the second person named "john" who signs up will hit an error.

1. Using a single letter is a popular practice in testing. An instructor could hit this and think that signup is not working at all.

2. the error message does not currently support custom messaging, such as to say pick a different username.

3. the placeholder cannot support this messaging.

**Comment by omniczech** [comment]
Now has an error with more descriptive text

**Comment by aubreezy0** [comment]
Does the job nicely.
