### ISSUE TITLE
signup form clears / no next step

### ISSUE THREAD

**Issue by aubreezy0** [team-jorgie/team-project-front-end#23]
User doesn't have direction for what to do after signup.

1. success message only says signup successful

Options:
- show sign in tab on submit
- update message with "now please sign in"

2. success message is very very difficult to see. See #20 for details

![image](https://user-images.githubusercontent.com/36781350/39970107-fa0c5f1e-56b3-11e8-8df2-557f5aa8f36d.png)

**Comment by omniczech** [comment]
Sign up now passes data to sign the user in automatically.
