### ISSUE TITLE
"my files" text is below results

### ISSUE THREAD

**Issue by aubreezy0** [team-jorgie/team-project-front-end#27]
After adding a file, the header text " My Files" bumps to underneath the file. Should stay at the top.

![image](https://user-images.githubusercontent.com/36781350/39970308-24a2f94c-56b7-11e8-84bd-9cc35ac4794a.png)

**Comment by omniczech** [comment]
My files moved outside the div, given class to be targetable, prepend now doesn't look like trash

**Comment by aubreezy0** [comment]
Looking to verify the fix will also address this:

![image](https://user-images.githubusercontent.com/36781350/39970555-653f34a8-56bb-11e8-88c3-be8574f5939b.png)

**Comment by omniczech** [comment]
Yes, class was added to make sure the original was removed before the new one was added!
